import type { Application, InterviewJob, UserProfile } from "./types";

export const DEMO_PASSWORD = "demo1234";

export const seedUsers: UserProfile[] = [
  {
    id: "user-1",
    email: "user@demo.jp",
    name: "佐藤 美咲",
    role: "user",
    gender: "女性",
    age: 32,
    prefecture: "東京都",
    occupation: "会社員（マーケティング）",
    bio: "消費財・アプリのユーザーインタビューに多数参加経験があります。",
    createdAt: "2026-08-01T10:00:00+09:00",
  },
  {
    id: "user-2",
    email: "tanaka@demo.jp",
    name: "田中 健太",
    role: "user",
    gender: "男性",
    age: 41,
    prefecture: "大阪府",
    occupation: "会社員（人事）",
    bio: "BtoB領域のヒアリング経験あり。",
    createdAt: "2026-08-05T10:00:00+09:00",
  },
  {
    id: "company-1",
    email: "company@demo.jp",
    name: "鈴木 一郎",
    role: "company",
    companyName: "株式会社ノヴァプロダクト",
    createdAt: "2026-07-15T10:00:00+09:00",
  },
  {
    id: "company-2",
    email: "hr@demo.jp",
    name: "高橋 恵",
    role: "company",
    companyName: "株式会社クリアHR",
    createdAt: "2026-07-20T10:00:00+09:00",
  },
  {
    id: "admin-1",
    email: "admin@demo.jp",
    name: "運営管理者",
    role: "admin",
    createdAt: "2026-07-01T10:00:00+09:00",
  },
];

export const seedJobs: InterviewJob[] = [
  {
    id: "job-1",
    companyId: "company-1",
    companyName: "株式会社ノヴァプロダクト",
    title: "家事代行サービスを検討中の方にお話を伺いたいです",
    description:
      "新規家事代行サービスのコンセプト検証のため、日頃の家事負担や外部サービス利用意向について60分程度お伺いします。正解のないヒアリングですので、率直なご意見をお聞かせください。",
    conditions: [
      "20〜40代の方",
      "共働き世帯、またはお子さまがいらっしゃる方",
      "家事代行・クリーニング等の利用経験がある、または検討したことがある方",
    ],
    reward: 6000,
    durationMin: 60,
    recruitCount: 5,
    method: "online",
    tool: "Google Meet",
    recording: true,
    status: "published",
    deadline: "2026-09-25T23:59:00+09:00",
    screeningQuestions: [
      {
        id: "q1",
        type: "single",
        label: "現在のご職業を教えてください",
        required: true,
        options: ["会社員", "主婦・主夫", "フリーランス", "その他"],
      },
      {
        id: "q2",
        type: "single",
        label: "家事代行サービスの利用経験はありますか？",
        required: true,
        options: ["利用したことがある", "検討したことがある", "ない"],
      },
      {
        id: "q3",
        type: "text",
        label: "日頃、特に負担に感じる家事があれば教えてください",
        required: false,
      },
    ],
    createdAt: "2026-09-01T09:00:00+09:00",
    applicantCount: 12,
  },
  {
    id: "job-2",
    companyId: "company-2",
    companyName: "株式会社クリアHR",
    title: "人事・研修ご担当の方に社内研修の実態をお伺いしたい",
    description:
      "企業向け研修サービスの改善のため、社員300名以上の企業で人事・研修を担当されている方に、現状の課題や選定基準についてインタビューさせてください。",
    conditions: [
      "社員数300名以上の企業にお勤めの方",
      "人事・人材開発・研修企画に関わっている方",
      "直近1年以内に社内研修の企画・実施に関わった方",
    ],
    reward: 10000,
    durationMin: 60,
    recruitCount: 3,
    method: "online",
    tool: "Zoom",
    recording: true,
    status: "published",
    deadline: "2026-09-20T23:59:00+09:00",
    screeningQuestions: [
      {
        id: "q1",
        type: "single",
        label: "現在の勤務先の従業員規模を教えてください",
        required: true,
        options: ["〜299名", "300〜999名", "1,000名以上"],
      },
      {
        id: "q2",
        type: "multi",
        label: "担当している業務に近いものをすべて選んでください",
        required: true,
        options: ["採用", "研修企画", "評価制度", "労務", "その他"],
      },
    ],
    createdAt: "2026-09-03T11:00:00+09:00",
    applicantCount: 8,
  },
  {
    id: "job-3",
    companyId: "company-1",
    companyName: "株式会社ノヴァプロダクト",
    title: "ふるさと納税をこれから始めたい方へヒアリング",
    description:
      "ふるさと納税サービスのUX改善のため、これから利用を検討している方の不安点・情報収集の進め方について30分お話を伺います。",
    conditions: [
      "これからふるさと納税を始めようと考えている方",
      "寄付先の決定権をご自身でお持ちの方",
      "20〜50代の方",
    ],
    reward: 3500,
    durationMin: 30,
    recruitCount: 8,
    method: "online",
    tool: "Google Meet",
    recording: false,
    status: "published",
    deadline: "2026-09-18T23:59:00+09:00",
    screeningQuestions: [
      {
        id: "q1",
        type: "single",
        label: "ふるさと納税の利用状況を教えてください",
        required: true,
        options: ["これから始めたい", "過去に利用したことがある", "利用予定はない"],
      },
    ],
    createdAt: "2026-09-05T14:00:00+09:00",
    applicantCount: 21,
  },
  {
    id: "job-4",
    companyId: "company-2",
    companyName: "株式会社クリアHR",
    title: "在宅ワーク中心の働き方についてのインタビュー",
    description:
      "ハイブリッドワーク支援ツールの企画にあたり、週3日以上在宅で働く方のコミュニケーション課題を伺います。",
    conditions: [
      "週3日以上在宅勤務している方",
      "30代の会社員の方",
      "チームでのオンライン会議が週2回以上ある方",
    ],
    reward: 7000,
    durationMin: 45,
    recruitCount: 4,
    method: "online",
    tool: "Microsoft Teams",
    recording: true,
    status: "pending_review",
    deadline: "2026-09-28T23:59:00+09:00",
    screeningQuestions: [
      {
        id: "q1",
        type: "single",
        label: "週あたりの在宅勤務日数はどのくらいですか？",
        required: true,
        options: ["1〜2日", "3〜4日", "ほぼ毎日"],
      },
    ],
    createdAt: "2026-09-08T10:00:00+09:00",
    applicantCount: 0,
  },
  {
    id: "job-5",
    companyId: "company-1",
    companyName: "株式会社ノヴァプロダクト",
    title: "スキンケアの悩みについてお話を伺いたいです",
    description:
      "化粧品ブランドの新商品開発のため、肌に合わないと感じたご経験のある方へインタビューを実施します。",
    conditions: [
      "化粧水・乳液などを日常的に使用している方",
      "肌に合わないと感じた経験がある方",
      "性別・年齢問いません",
    ],
    reward: 8000,
    durationMin: 45,
    recruitCount: 6,
    method: "online",
    tool: "Zoom",
    recording: true,
    status: "published",
    deadline: "2026-09-22T23:59:00+09:00",
    screeningQuestions: [
      {
        id: "q1",
        type: "text",
        label: "肌に合わないと感じた具体的なエピソードを教えてください",
        required: true,
      },
    ],
    createdAt: "2026-09-06T16:00:00+09:00",
    applicantCount: 15,
  },
];

export const seedApplications: Application[] = [
  {
    id: "app-1",
    jobId: "job-1",
    userId: "user-1",
    userName: "佐藤 美咲",
    userAge: 32,
    userPrefecture: "東京都",
    userOccupation: "会社員（マーケティング）",
    status: "selected",
    answers: {
      q1: "会社員",
      q2: "検討したことがある",
      q3: "平日の夕食準備と洗濯が特に負担です。",
    },
    proposedSlots: [
      "2026-09-15T19:00:00+09:00",
      "2026-09-16T20:00:00+09:00",
      "2026-09-17T12:00:00+09:00",
    ],
    createdAt: "2026-09-07T20:00:00+09:00",
    updatedAt: "2026-09-09T11:00:00+09:00",
  },
  {
    id: "app-2",
    jobId: "job-2",
    userId: "user-2",
    userName: "田中 健太",
    userAge: 41,
    userPrefecture: "大阪府",
    userOccupation: "会社員（人事）",
    status: "confirmed",
    answers: {
      q1: "300〜999名",
      q2: ["研修企画", "評価制度"],
    },
    proposedSlots: ["2026-09-14T15:00:00+09:00"],
    confirmedSlot: "2026-09-14T15:00:00+09:00",
    meetingUrl: "https://zoom.us/j/1234567890",
    createdAt: "2026-09-06T09:30:00+09:00",
    updatedAt: "2026-09-08T16:00:00+09:00",
  },
  {
    id: "app-3",
    jobId: "job-3",
    userId: "user-1",
    userName: "佐藤 美咲",
    userAge: 32,
    userPrefecture: "東京都",
    userOccupation: "会社員（マーケティング）",
    status: "applied",
    answers: {
      q1: "これから始めたい",
    },
    proposedSlots: [],
    createdAt: "2026-09-09T21:00:00+09:00",
    updatedAt: "2026-09-09T21:00:00+09:00",
  },
  {
    id: "app-4",
    jobId: "job-5",
    userId: "user-1",
    userName: "佐藤 美咲",
    userAge: 32,
    userPrefecture: "東京都",
    userOccupation: "会社員（マーケティング）",
    status: "rejected",
    answers: {
      q1: "敏感肌で新しい化粧水を試すと赤みが出ることがあります。",
    },
    proposedSlots: [],
    createdAt: "2026-09-07T12:00:00+09:00",
    updatedAt: "2026-09-08T10:00:00+09:00",
  },
];
